### ISSUE TITLE
Scripts for Post-LN in Figure 10?

### ISSUE THREAD

**Issue by zhuchen03** [LiyuanLucasLiu/Transformer-Clinic#16]
Hi Liyuan,

Thank you for sharing the code! The current version already includes lots of details.

Could you share the script for training the Post-LN Transformer without learning rate warmup (nor Admin) in Figure 10? I tried lr=3e-4, beta2=0.999, warmup-updates=1 using RAdam and the inverse square root schedule, but the model does not seem to converge.

**Comment by LiyuanLucasLiu** [comment]
Thanks for reaching out! I just added some lines in [the recipe](https://github.com/LiyuanLucasLiu/Transformer-Clinic/blob/master/nmt-experiments/iwslt14_de-en.md#no-warmup). 

This part of experiments is an extension of our previous work [RAdam](https://github.com/LiyuanLucasLiu/RAdam) and uses a linear learning rate scheduler. We didn't use this setting (linear scheduler) in our main experiments for a more fair comparison (since typical existing Transformer NMT models are trained with the inverse_sqrt scheduler, I decide to stick to that). I would update the arXiv version with this part of information. 

Happy Holidays!
