### ISSUE TITLE
Do the embedding layer's layernorm parameters need to be reparameterized accordingly?

### ISSUE THREAD

**Issue by gotobelieve** [LiyuanLucasLiu/Transformer-Clinic#5]
hi, According to appendix C in the paper, i am not sure whether the embedding layer's layernorm parameters need to be reparameterized accordingly, if not, it means that the attention_ratio_change in the first transformer layer is not used in the reparameterization process? By the way, does the bias term has been taken into consideration in all self-attention layers? Thank you very much!

**Comment by LiyuanLucasLiu** [comment]
The reparameterization aims to convert Admin back to the vanilla Transformer for a better compatibility, otherwise this process is not necessary. 

To this end, the first attention_ratio_change needs to be token care of. For some models, a layer norm is added after the embedding, while for others not. If the layer norm is not available, then the embedding weight needs to be re-scaled accordingly (and weight sharing needs to be stopped). 

For the bias term, I believe the deviation in Appendix C gives clear explanations on necessary transformations for bias terms.
